# Generated by Django 5.2.7 on 2025-10-20 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_date'], 'verbose_name': 'Post del Blog', 'verbose_name_plural': 'Posts del Blog'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_date'], 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category', 'order', 'name'], 'verbose_name': 'Habilidad', 'verbose_name_plural': 'Habilidades'},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
